import assert from 'node:assert/strict';
import {searchScope} from './careerPolicy.js';
import {evaluateJobEligibility} from './jobEligibility.js';
import {analyzeCompleteness} from './knowledgeBase.js';
import {runCareerAgent as runAgent} from './careerAgent.js';
const runCareerAgent = args => runAgent({...args,brainModel:async()=>({content:[{type:'text',text:JSON.stringify({intents:['search'],subject:'current',objective:'寻找岗位',facts:[],questions:[]})}]})});
const user=content=>({role:'user',content});
assert.deepEqual(searchScope([user('帮我找工作')]),{region:null,type:null});
assert.deepEqual(searchScope([{role:'assistant',content:'国内实习'},user('帮我找工作')]),{region:null,type:null});
assert.deepEqual(searchScope([user('只考虑国内实习岗位')]),{region:'domestic',type:'internship'});
assert.deepEqual(searchScope([user('国内校招岗位'),user('不要校招，找实习')]),{region:'domestic',type:'internship'});
const profile={name:'测试',contact:{email:'x@example.com'},education:['某大学 计算机本科 2024–2028'],skills:['React'],projects:['React 搜索项目'],experience:[],awards:[],metrics:[]};
const job={title:'2026届前端校招',type:'campus',location:'上海',description:'计算机本科，React前端业务开发',postingAge:'1d'};
assert.equal(evaluateJobEligibility(job,profile,{type:'campus',region:'domestic'}).checks.find(c=>c.dimension==='graduation').status,'fail');
assert.equal(evaluateJobEligibility({...job,location:'United States'},profile,{region:'domestic'}).checks.find(c=>c.dimension==='region').status,'fail');
assert.equal(evaluateJobEligibility(job,profile,{type:'social'}).checks.find(c=>c.dimension==='job_type').status,'fail');
const diagnosis=analyzeCompleteness(profile);
assert(!diagnosis.missing.some(f=>['projects','skills','awards'].includes(f.id)));
const c={id:'policy',context:{},messages:[user('帮我推荐岗位')]};
await runCareerAgent({conversation:c,persist:()=>{},emit:()=>{},model:async()=>({content:[{type:'text',text:'最推荐微软博士实习：https://example.com/fake'}]})});
assert.doesNotMatch(c.messages.at(-1).content,/微软|example.com/);
assert.match(c.messages.at(-1).content,/国内.*海外/);
let searched=false;
const c2={id:'scope',context:{},messages:[user('帮我找工作')]};
let calls=0;
await runCareerAgent({conversation:c2,persist:()=>{},emit:()=>{},search:async()=>{searched=true;return {jobs:[]}},model:async()=> ++calls===1?{content:[{type:'tool_use',id:'s',name:'search_jobs',input:{query:'AI',type:'campus'}}]}:{content:[{type:'text',text:'已推荐'}]}});
assert.equal(searched,false);
console.log('Career SOP regressions passed: scope, cohort, region, type, completeness, fabricated recommendations');
