import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {createJobKnowledge,normalizeFeedJob,JOB_RETENTION} from './jobKnowledge.js';
const db=new DatabaseSync(':memory:');
db.exec('CREATE TABLE users(id TEXT); INSERT INTO users VALUES ("keep");'.replace('"keep"',"'keep'"));
let now=Date.parse('2026-09-08T00:00:00Z'),calls=0,fail=false;
const feed={id:'fixture'};
const row={company_name:'测试公司',title:'前端实习',official_url:'https://example.com/jobs/1?utm_source=x',location:'上海',job_type:'实习',jd_text:'真实岗位描述',last_seen:new Date(now).toISOString()};
const service=createJobKnowledge(db,{clock:()=>now,feeds:[feed],loader:async()=>{calls++;if(fail)throw new Error('offline');return [row,{...row,official_url:'https://example.com/jobs/1'}];}});
assert.equal(normalizeFeedJob({...row,last_seen:''},feed,now),null);
assert.equal(normalizeFeedJob({...row,official_url:'javascript:alert(1)'},feed,now),null);
await service.sync();assert.equal(calls,1);
let result=await service.search({query:'前端',type:'internship'});
assert.equal(result.jobs.length,1);assert.equal(result.jobs[0].fullDescriptionVerified,false);assert.equal(calls,1);
const restarted=createJobKnowledge(db,{clock:()=>now,feeds:[feed],loader:async()=>{throw new Error('must not refresh early')}});
await restarted.sync();assert.equal((await restarted.search({query:'前端'})).jobs.length,1);
now+=JOB_RETENTION.refreshMs;fail=true;await service.sync();
assert.equal((await service.search({query:'前端'})).jobs.length,1);
now+=JOB_RETENTION.freshMs;fail=false;await service.sync();
assert.equal((await service.search({query:'前端'})).jobs.length,0);
assert.equal(db.prepare('SELECT COUNT(*) n FROM job_knowledge_records WHERE archived_at IS NOT NULL').get().n,1);
now+=JOB_RETENTION.archiveMs+86400000;service.cleanup(true);await service.sync({force:true});
assert.equal(db.prepare('SELECT COUNT(*) n FROM job_knowledge_records').get().n,0);
assert.equal(db.prepare('SELECT id FROM users').get().id,'keep');
assert.equal(db.prepare('SELECT COUNT(*) n FROM job_knowledge_runs').get().n,1);
// A second worker cannot synchronize a source while the first holds its lease.
let release,otherCalls=0;
const owner=createJobKnowledge(db,{clock:()=>now,feeds:[{id:'lease'}],loader:()=>new Promise(resolve=>{release=()=>resolve([{...row,last_seen:new Date(now).toISOString()}]);})});
const other=createJobKnowledge(db,{clock:()=>now,feeds:[{id:'lease'}],loader:async()=>{otherCalls++;return [row]}});
const running=owner.sync({force:true});await other.sync({force:true});assert.equal(otherCalls,0);release();await running;
await service.stop();db.close();
console.log('Background knowledge tests passed: sync, dedup, failure retention, freshness, cleanup, restart, lease, read-only search');
